upstream ask_vasutenko {
    server 127.0.0.1:8000;
}

proxy_cache_path /Users/rvasutenko/Desktop/Technopark/Technopark/nginx_cache
                 levels=1:2
                 keys_zone=ask_vasutenko_zone:10m
                 inactive=24h
                 max_size=50m;

server {
    listen 80 default_server;
    server_name ask_vasutenko.com;

    error_log /opt/homebrew/var/log/nginx/ask_vasutenko_error.log;
    access_log /opt/homebrew/var/log/nginx/ask_vasutenko_access.log;

    location ^~ /uploads {
        root /Users/rvasutenko/Desktop/Technopark/Technopark/ask_vasutenko;
        add_header Cache-Control "public, max-age=3600";
        gzip on;
        gzip_types text/plain image/jpeg image/jpg image/png;
    }

    location ~* \.(html|js|css|jpeg|jpg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
        root /Users/rvasutenko/Desktop/Technopark/Technopark/ask_vasutenko;
        try_files $uri /static/$uri =404;
        add_header Cache-Control "public, max-age=3600";
        gzip on;
        gzip_types text/css application/javascript image/svg+xml image/jpeg image/jpg image/png;
    }

    location / {
        proxy_pass http://ask_vasutenko;
        proxy_set_header Host $host;
        proxy_cache ask_vasutenko_zone;
        proxy_cache_valid 200 302 10m;
        proxy_cache_valid 404      1m;
    }
}

