# Generated by Django 4.2.3 on 2024-12-21 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerlike",
            name="is_dislike",
            field=models.BooleanField(default=False, verbose_name="Дизлайк"),
        ),
        migrations.AddField(
            model_name="questionlike",
            name="is_dislike",
            field=models.BooleanField(default=False, verbose_name="Дизлайк"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(5000)],
                verbose_name="Содержание",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(5000)],
                verbose_name="Описание",
            ),
        ),
    ]
