# Generated by Django 4.2.3 on 2024-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_answerlike_is_dislike_questionlike_is_dislike_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
    ]
