# Generated by Django 4.2.3 on 2024-12-21 14:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_alter_question_likes_count"),
    ]

    operations = [
        migrations.RenameModel(old_name="AnswerLike", new_name="AnswerRate",),
        migrations.RenameModel(old_name="QuestionLike", new_name="QuestionRate",),
        migrations.RenameField(
            model_name="question", old_name="likes_count", new_name="rating",
        ),
    ]
