# Generated by Django 4.2.3 on 2024-12-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_answerlike_answerrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer", name="rating", field=models.IntegerField(default=0),
        ),
    ]
