# Generated by Django 4.2.3 on 2024-12-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_answer_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Правильный ответ"),
        ),
    ]
