# Generated by Django 4.2.3 on 2024-12-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_answer_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerrate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Поставлен"
            ),
        ),
        migrations.AlterField(
            model_name="answerrate",
            name="is_dislike",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Дизлайк"
            ),
        ),
        migrations.AlterField(
            model_name="questionrate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Поставлен"
            ),
        ),
        migrations.AlterField(
            model_name="questionrate",
            name="is_dislike",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Дизлайк"
            ),
        ),
    ]
