# Generated by Django 4.2.3 on 2024-12-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_answerrate_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="a_likes_count",),
        migrations.RemoveField(model_name="profile", name="q_likes_count",),
        migrations.AddField(
            model_name="profile",
            name="a_likes_last_week",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="q_likes_last_week",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_popularity",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
