# Generated by Django 4.2.3 on 2024-12-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_profile_a_likes_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="likes_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="likes_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
