# Generated by Django 4.2.3 on 2024-12-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_answer_likes_count_question_likes_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="answer", name="likes_count",),
        migrations.RemoveField(model_name="question", name="likes_count",),
        migrations.AlterField(
            model_name="answer",
            name="rating",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="rating",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
