# Generated by Django 4.2.3 on 2024-12-25 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0010_remove_answer_likes_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="a_likes_last_week",),
        migrations.RemoveField(model_name="profile", name="q_likes_last_week",),
        migrations.RemoveField(model_name="profile", name="total_popularity",),
        migrations.AlterField(
            model_name="answerrate",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="app.answer",
                verbose_name="Ответ",
            ),
        ),
        migrations.AlterField(
            model_name="answerrate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_rates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="questionrate",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="app.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="questionrate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_rates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
